name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Retrieve version
      id: get_version
      run: |
        VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
        echo "::set-output name=version::$VERSION"    
    - name: Build with Maven
      run: mvn clean package
    - uses: actions/upload-artifact@v1
      with:
        name: "Velt-${{ steps.get_version.outputs.version }}.jar"
        path: "target/Velt-${{ steps.get_version.outputs.version }}.jar"
